namespace CHIA_RPC.HelperFunctions_NS
{
    /// <summary>
    /// ActionResult<typeparamref name="T"/> represents the result of json deserialisation or any other action which might fail 
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public class ActionResult<T>
    {
        /// <summary>
        /// creates a new Actionresult object
        /// </summary>
        /// <param name="actionInput">the raw input for the action, nessesary for debugging purposes</param>
        public ActionResult(string actionInput) { RawJson = actionInput; }
        /// <summary>
        /// indicates if the action was successful
        /// </summary>
        public bool Success { get; set; }
        /// <summary>
        /// the object generated by the action
        /// </summary>
        public T? Data { get; set; }
        /// <summary>
        /// contains the error Message if not successful
        /// </summary>
        public string? Error { get; set; }
        /// <summary>
        /// Contains the raw input that was given to the action in case of error
        /// </summary>
        public string RawJson { get; set; }
    }
}
