using CHIA_RPC.HelperFunctions_NS;

namespace CHIA_RPC.Wallet_NS.DID_NS
{
    /// <summary>
    /// Response class for the Create Attest functionality.
    /// </summary>
    /// <remarks>
    /// <see href="https://docs.chia.net/did-rpc#did_create_attest"/><br/><br/>
    /// uses:<br/><see cref="DidCreateAttest_RPC"/>
    /// </remarks>
    public class DidCreateAttest_Response : ResponseTemplate<DidCreateAttest_Response>
    {
        /// <summary>
        /// The attest data generated by the command.
        /// </summary>
        public string attest_data { get; set; }

        /// <summary>
        /// Additional information about the attest.
        /// </summary>
        public List<object> info { get; set; }

        /// <summary>
        /// The message spend bundle.
        /// </summary>
        public string message_spend_bundle { get; set; }
    }

    /// <summary>
    /// Response from the did_create_attest RPC command
    /// </summary>
    /// <remarks><see href="https://docs.chia.net/did-rpc#did_create_attest"/></remarks>
    /// <returns><see cref="DidCreateAttest_Response"/></returns>
    public class DidCreateAttest_RPC : RPCTemplate<DidCreateAttest_RPC>
    {
        /// <summary>
        /// The Wallet ID for which to create the attest
        /// </summary>
        /// <remarks>mandatory</remarks>
        public int wallet_id { get; set; }

        /// <summary>
        /// The coin to use for the attest
        /// </summary>
        /// <remarks>mandatory</remarks>
        public string coin_name { get; set; }

        /// <summary>
        /// The public key to use for the attest
        /// </summary>
        /// <remarks>mandatory</remarks>
        public string pubkey { get; set; }

        /// <summary>
        /// The puzzle hash to use for the attest
        /// </summary>
        /// <remarks>mandatory</remarks>
        public string puzhash { get; set; }
    }
}
