name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore "CHIA-RPC/CHIA-RPC.csproj"

    - name: Build
      run: dotnet build --no-restore "CHIA-RPC/CHIA-RPC.csproj"

    #- name: Test
      #run: dotnet test "path/to/YourTestProject.csproj" --no-build --verbosity normal # Specify the path to your test project file

