name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore "path/to/YourMainProject.csproj" # Specify the path to your main project file

    - name: Build
      run: dotnet build "path/to/YourSolutionFile.sln" --no-restore -c Release # Specify the path to your solution file

    - name: Test
      run: dotnet test "path/to/YourTestProject.csproj" --no-build --verbosity normal # Specify the path to your test project file

