name: .NET

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Use v2 of actions/checkout
    - name: Setup .NET
      uses: actions/setup-dotnet@v2  # Use v2 of actions/setup-dotnet
      with:
        dotnet-version: 6.0.x
    - name: Clear NuGet Cache
      run: dotnet nuget locals all --clear
    - name: Restore dependencies
      run: |
        echo "Restoring dependencies..."
        dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

